name: Tests

on:
  push:
    branches: [ main, accelerate-with-copilot ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test coverage (optional)
      run: |
        pip install pytest-cov
        pytest tests/ --cov=src --cov-report=term-missing
